image:
    repository: kong/kong-gateway
    tag: "3.1"
env:
    prefix: ENC[AES256_GCM,data:3X9LuNdgMO5JzZ2Fjg==,iv:vKqzIHoqDQlAIpUqBwevVMH/bNSAAcmqJdLQ5/arTaM=,tag:4NpyPRkIj6jADAaRSkx9lw==,type:str]
    log_level: ENC[AES256_GCM,data:O3wLuG8=,iv:MlJ7kuNIV85JB0sUmi6V4I9QZrs2etBL0qdALxnYdZE=,tag:tEbzMQ+M13xlxE3VdDjx/Q==,type:str]
    database: ENC[AES256_GCM,data:Tq4u2X8q9To=,iv:p4uYLv88fLqxzw6tYslgGz7NTeTS+Iw683mjZ8Z/Drs=,tag:gzAjgoAHTvDQ4wQg5vr3eA==,type:str]
    proxy_url: ENC[AES256_GCM,data:E8NUnVoh5OA6WMZgfWCOX7qoYbMR7YTOxO0=,iv:TFwtIqiYjF3CIOSk67Bhn2jbftXXwyUCDqZFOmFvunE=,tag:cuip0lyi3J2AE85NWGLEvQ==,type:str]
    admin_gui_url: ENC[AES256_GCM,data:Wgq9UhsrzTOzUbTUhCQAC9/ypS9h8/FhpPo=,iv:PFqahpHyJWQZxMBcupZWyNjI0Qn2M9oYOOjXUsQlpyk=,tag:1ZBKyQzoljWEikKpcyJkKQ==,type:str]
    admin_api_uri: ENC[AES256_GCM,data:t7LNJxbpCQ5zuBa2wxxreSl3WphqXxOmWlM=,iv:7H7VyAezSRrLHYwE+2hSPmS+pLkAiHHSB0xfdlZBDV4=,tag:PxugCNA5LXOXfA3ZD8Ef5g==,type:str]
    password: ENC[AES256_GCM,data:srYQxQ==,iv:u41uO6X/n4IjyxWhM1aBneUkUauP15uK7KN6xO34k8s=,tag:l2kE6Qbj97aQZBURBHqERA==,type:str]
admin:
    enabled: ENC[AES256_GCM,data:AHcRDg==,iv:2YMfVF3REmE6Ld/SSCsgkBgrApFJ4QrN4NDq6EzEyFE=,tag:xowKeKrtDIwnlugYUVBnqA==,type:bool]
    type: ENC[AES256_GCM,data:5xqwqeWMEN8=,iv:vnXA8RAuPRK3p2WdIl+onvBHbmQg0MuAk9ELchJrNRY=,tag:3i1y6Kmz27r73NiDNDQOMw==,type:str]
    annotations:
        konghq.com/protocol: ENC[AES256_GCM,data:/lQ0JTM=,iv:gIeZST/+7/2lM5unErq4Knmjp0XYGHCxRr2vmYpK3yw=,tag:bYSfPkoFu0C2pRtJG32zBA==,type:str]
    http:
        #ENC[AES256_GCM,data:ptOjEAOO9Rc4TZ1CjJmTnDtOiXPCs5KBbMny6gIf+NR3ah/OSZdFO4ue1g0g6AI=,iv:V1xLs2n9WIeLl9hw8Tr7Ut9ARW8iOqk87dvAOMVymgY=,tag:XtFeaVdBSdmJTWywIB/pjg==,type:comment]
        #ENC[AES256_GCM,data:BzY4Sx07qT53Kz0xiO4XwYNhO2axu7V7n3Isa80FTfHbNdiwR6S4kVKhequ4yxS6PQKDj4bFHNZzNACQCyRv57CmxwAu1gkJxrsa4v7yMeUA,iv:K0TsN8CqEdH7NGgh8Ol+ft/KF8mX3YutyQTO10puLso=,tag:pgQI07Fhzqzds1Re+jUGWw==,type:comment]
        enabled: ENC[AES256_GCM,data:H3yC/g==,iv:FFnBST2Tq3mgwLaZhTitaAigkOrDtbiNIkcASyivulw=,tag:L3dElYs/2RD2xxkpGn6QvQ==,type:bool]
        servicePort: ENC[AES256_GCM,data:RlHe5Q==,iv:flqI4BUs8IyJCrv6Oys8YvnPq65zTRxNp7YiKdvOVy8=,tag:TaR31qALy9tPbaJMC1PqxA==,type:int]
        containerPort: ENC[AES256_GCM,data:+1HlLA==,iv:1HeY0omyhrDPWCckb/g4X3Vuw2Mb16DApbvE/v/4LzI=,tag:ZX1VjRWV2lB4urBhoWb7VQ==,type:int]
        #ENC[AES256_GCM,data:Mm8Ciw/cKzV2bHnkKDcYuzZiJdUtPvNl0gF4Adj6BzeNp79OrbC1uBNCUXY7Ayte9WFVKiKN05XsPeXHKYM=,iv:l+tzi8yalS+zMqT45MZNQ9lYMlCz5YjagF0uaj2ERbs=,tag:huahPbvPeT0sD2d6dXjZ6w==,type:comment]
        nodePort: ENC[AES256_GCM,data:UIHWZBA=,iv:zsUYoe/ZEzQ/CNjOuNGAWI43nZnrlEMc/1adATdV/zg=,tag:PA6ppeSYJ+8aXg8DhVp5Qw==,type:int]
        #ENC[AES256_GCM,data:Z+QUvG06ZKGXh+xcxxP93iv0aPQYIJlgLOHjWomwEMY0Pezgs5odXnkeSHYSl9DxshVyjOkIo1n2cfCaDUhuEQ==,iv:XXmVCsuiDfxcSqS3Mg1RcjybfszXgee4N+2drI/IOJU=,tag:ECRrn/laESpcmUI3h9EcTg==,type:comment]
        parameters: []
    tls:
        enabled: ENC[AES256_GCM,data:gOo7QDM=,iv:Wz1L42QpUYGkH/TlSgfv7nhkComFKcGW1sB4Dx3RpYA=,tag:Yj7rKSyY9BFYzr0IxpMppw==,type:bool]
    ingress:
        enabled: ENC[AES256_GCM,data:gH46HB0=,iv:VvV3bfcUn3tRE4L70vJaFdRP0Irf1eEzSoP2AvzmNiU=,tag:QAg/Fm5cS4UoPbgtViG+3w==,type:bool]
proxy:
    enabled: ENC[AES256_GCM,data:6f1hKQ==,iv:LQ4QeLTd3iy7w4bIHmQJG8TL0uMGOtk/mZUuEgZu0IY=,tag:25JadRE1FTQO4T3IXhCjJA==,type:bool]
    type: ENC[AES256_GCM,data:1bc+0ybNw9k=,iv:t1QeZrs0F9RAu+pHKj+NaIQtR9uvH3vCH33Y5/StKOU=,tag:SNgYY34ahSU0RMVnIVDZOQ==,type:str]
    annotations: {}
    http:
        #ENC[AES256_GCM,data:9ZAtuBiTBuvBzGwlQwFVbHZlGi421dXbTbcXOe8m+fz52vtblPKJXpRGzQ==,iv:XStoIx/qEpr3oLVyRw6gfsSbcM9S46pWlh6tpTOO2vc=,tag:K2zaCvA+22XD4DiixfoYTg==,type:comment]
        enabled: ENC[AES256_GCM,data:GyZ6iQ==,iv:AEaFNkQ+7v9ezVzj8JqyTtTWufeFxTnmoXVj+N6vwmc=,tag:UpQMUQSu48FOpgP2uncXCA==,type:bool]
        servicePort: ENC[AES256_GCM,data:XfY=,iv:SKHq2dNtYaaezs9nZQVBIsTEAM2LtA/FCpKuKhmMfQ4=,tag:tnt/ovYcDbnihPveR6Tofg==,type:int]
        containerPort: ENC[AES256_GCM,data:NZmjgQ==,iv:ttlme4w57MlELWJTuZ589XvZ3LmmKztPtXs7RP88trk=,tag:vbFDTHfQ3j9EI6W1n1IT4w==,type:int]
        #ENC[AES256_GCM,data:EabPqs5XFYEZRvNX2OEzC9AD0XOqLjh7pfFIATknBrCeN1lEhROYvwX6ZLVSDo62xw5K8gTGjznBJqNHA4U=,iv:CUMxkUHHzOS7WRTIDb95o4DT8lVDZ1lWdD9COehMgR0=,tag:hLL3IwUaZVAPLHiijEMikw==,type:comment]
        nodePort: ENC[AES256_GCM,data:hBBTV7Y=,iv:qWvTa2tgbW8uJ3JPZtXr1clM12xIkIXSkz8cd4y4Pew=,tag:R18sfyJOBAF5vcjEo39yFg==,type:int]
        #ENC[AES256_GCM,data:F0wUG7G6WULhTW06WzaJYdHxS7R4fv6mj0lhveD1IbTztL2bo1wu9QH7wg+2AU7Uy5SKNRWfzgufqU8nUUfbpg==,iv:TgsrcUyV4OiiDWxHxrSuuwgesINDSW7Q4+3FBnORh0Q=,tag:3NUnTOMa6VdV1OmwZnhkKA==,type:comment]
        parameters: []
    tls:
        enabled: ENC[AES256_GCM,data:V3Wne94=,iv:CPlebcX1VfuMJ1tN20wl2BJ8V25hqYT/lX0CqHQe6ew=,tag:8dk7TH1s6MgOguqLc65hqQ==,type:bool]
    stream: {}
    ingress:
        enabled: ENC[AES256_GCM,data:NhoCRfM=,iv:89FCUn3cjSMlEhSteeDQGq/356wSR1DWui4qM8JvZeM=,tag:Kx490m5y0Ur5vrfKSlZEBA==,type:bool]
    externalIPs: []
enterprise:
    enabled: ENC[AES256_GCM,data:tXtzn4A=,iv:07jksFvwt47bCwACvq3EFIuNIC4e7DNxTo14z0fglrI=,tag:kPa54KFetgtp9F3ZA4JIvg==,type:bool]
    #ENC[AES256_GCM,data:ZxJOxY3DUMaQk4jbp5ji/NIcKQNUZe3xc9A+jSFKSI1EhsWcSgLNtTvXMbHNcyvpHgXIzvyUStYq3UaNcn0OPRCcm76Fm7ghz085LLER67TjcGdQMg0wgm8z3UQZ41yJgA==,iv:M066RCZUWQMX3QlLA8yFLijvjch3xYmhyQSRsotSLaM=,tag:OmLvf7aOeQYQUmBDUIzHvg==,type:comment]
    license_secret: ENC[AES256_GCM,data:1DXdqlKXiwxAww0VWvE3MZw+ir8VEq4=,iv:16HegAM58ceTk1MVU6OO5J6IemmQi+Kc3Nbzb8qqbV0=,tag:lXzj0bgyGEN1buv+SidGLg==,type:str]
    vitals:
        enabled: ENC[AES256_GCM,data:/cp2vkY=,iv:jP6Cexg+0NmOAQqJ2v7ZFAJQJVgCg9sddenZUceasyM=,tag:u4QoOzXBM9d557pm3byRAQ==,type:bool]
    portal:
        enabled: ENC[AES256_GCM,data:VAmCv8w=,iv:4abRSZmE/rRA8WGsUlFCmkzrD30p8xL1Nqn8mV9hDZg=,tag:vtti7nsPXkrR/NyoPxr+LQ==,type:bool]
    rbac:
        enabled: ENC[AES256_GCM,data:K7bna74=,iv:SVHSKzUXYapyoYS5e+mP/Y0Gld/gpd5yIDLR3TmN5uE=,tag:G/IQbj1ltvDQeoiAc3w0wg==,type:bool]
    smtp:
        enabled: ENC[AES256_GCM,data:Lrw+6RA=,iv:IRO2dfF8io0qxtaC/Ys1ab42iaXcqWPE2ojq6bS7wi4=,tag:bd5zKbMxVAnAvYiQBnuPCQ==,type:bool]
manager:
    enabled: ENC[AES256_GCM,data:sXQDZw==,iv:wlH6tOWKpD13XEsCiQlgPzAiTKeg4VQf/fsJpr01Cs0=,tag:DFvK8116KNLbkPR5J/HQ9w==,type:bool]
    type: ENC[AES256_GCM,data:gc0hL+7Y/NI=,iv:p2Ho5z3gxKs2ykpJ/8eNQbkoGXOU5I4mcZ4QBlCmqJ8=,tag:Rs58XIQ2PkRx/D8ueNgIYg==,type:str]
    annotations:
        konghq.com/protocol: ENC[AES256_GCM,data:QmuqK10=,iv:baBKtrazpMN+B+Z0I/C85IyelvpNDB1rEcO9VAGi188=,tag:xvKIxxJtsLtmQFnwOOwhew==,type:str]
    http:
        #ENC[AES256_GCM,data:Ub0vAWYOf8E8SGZG1Wkxa0qWrXPbadymCm51lFLdwS2Pued62Wh77p8G9nOX5w==,iv:f/A/9VqjdW1nb7CPlyNGREeKEVH42KPI8XvGJq2IaTA=,tag:gjWPVFjX4gvT5Xh37p5XQA==,type:comment]
        enabled: ENC[AES256_GCM,data:VurV2A==,iv:HTSnZGpMxhmvIRA/xsf4We0+2m3GHckv9y3SiDwRYGA=,tag:vjfcZ7XNppH92wR+4wXVYA==,type:bool]
        servicePort: ENC[AES256_GCM,data:RtFGvw==,iv:HBmCDHBoP2LEPmtDERgKCwK9PsTIIkYK1jPtqm5lbwI=,tag:01ar0eWxU/sWDNhc4lxH9g==,type:int]
        containerPort: ENC[AES256_GCM,data:BazRxw==,iv:d3LoAvm7naLQ9Jr+V4CdQFFvPksQXX28q+Tx3LzwX0s=,tag:R4mH6H+p/aU2Up3nxP9IxA==,type:int]
        #ENC[AES256_GCM,data:/lCTZ1aVitSNwveoiZhU8f1xrvin7G3uh2lrJ1NBTVbvTDIGcuod/DW/suJoEuGplILXHDzXeuOblq3IIzU=,iv:OzUGE8VfCirZ/9UcPVlNplB7vp88Io2UtBo+R8rA0BQ=,tag:lCucLf4W1iV6ZKH9EIWpwQ==,type:comment]
        nodePort: ENC[AES256_GCM,data:GY6xCqk=,iv:RuMDAq49FtDN1yoTIps6ujRSg8ummGMIUpEzaVhAVkY=,tag:RnUwnO1fOk/gFMUuelGBOw==,type:int]
        #ENC[AES256_GCM,data:G1p04u0lZW35rG9GxWHTpndZdDIwWGSeF81OcQB3Xbbd3x/nbYl3ArepjZYxWiqpVGF6E0XQyFDSlWOErRyjTA==,iv:bvvDiVt3xTT/hJanl774CB4y+/YzeTPZYVpArfy+vvo=,tag:fmoiOaYZaStcrh2qekQ0Xw==,type:comment]
        parameters: []
    tls:
        enabled: ENC[AES256_GCM,data:gWRWAQ4=,iv:264DX2/NdWUEw218BvR2jtkusSJuLY9fGnYSDfMC7X4=,tag:JxoSIzhe+xG56C2SFqE+Hg==,type:bool]
    ingress:
        enabled: ENC[AES256_GCM,data:0qb3iGc=,iv:UxbPLtNNlIreu6XGqQ2rj7MHv2Ouxpv7rLaidEARBKc=,tag:P46jZIcgAS3/RmoXc42Yqw==,type:bool]
    externalIPs: []
portal:
    enabled: ENC[AES256_GCM,data:BamuKq0=,iv:nfNXTmytyPY8jvM4+etyXCtLvKN8sSEU9t3Kj4c0f6Q=,tag:OPtZitbMS32Bz14uWG/udQ==,type:bool]
portalapi:
    enabled: ENC[AES256_GCM,data:r4foP14=,iv:tIJxq/k8XZTS/4gkGV5ULUoM9ic/xuXGQbLIui/tOjE=,tag:JZZwCRMHOwVxXnV6fV4PVw==,type:bool]
postgresql:
    enabled: ENC[AES256_GCM,data:Fh0VAw==,iv:B3znWrGbs4WJwI77lVZ9aJs8RySRyHUtrQDPXhiJ/8I=,tag:AnxjbdM4p1TrdJGwMbh2EA==,type:bool]
    postgresqlUsername: ENC[AES256_GCM,data:mBv/Qw==,iv:1fH5Yik8iOjR2pqlqtUW6BDj3s3U5CV7AgmhVjfQjZc=,tag:uS4GLl/+LNxHhpYeqEa4pQ==,type:str]
    postgresqlDatabase: ENC[AES256_GCM,data:/7+aEw==,iv:90WOuk37GUUjbJNsqlAVWbJdVzptlsi4ajAKZKroSRI=,tag:hNQ08rbEQzLBP7Ebh3nhzA==,type:str]
    postgresqlPassword: ENC[AES256_GCM,data:PYIebg==,iv:JZA47tIL2T9BHhuGhxy6Z9wDIjlQGaZFok54FnzxyLw=,tag:2iXxv+EEHC4AMBuPW67HLA==,type:str]
    service:
        port: ENC[AES256_GCM,data:O1Fpuw==,iv:vWLbKItQ93ETlUWtddKTf0jFzXnYJ0t+27cuFGAUtdk=,tag:QPUQsmMYZmPflwzXZ05MaA==,type:int]
ingressController:
    enabled: true
    installCRDs: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yfejy3x93l2x2w2wvmxzrkaeh8575vwsdxfal9ncdspgejtxxpssvl033f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NVhjWExZMG0xd21QYXBL
            bXh3Q3M0MWNOVVAzT3VwNjlvenNMd0pjOUFVCldjb3lmTGRQVjBTK2drTXI5T01K
            VS9Ta2xiRGNob1d3MGpqbjlEV2RLV2sKLS0tIE9WSkcxZW9ic2VYLzdBMmNWaTlW
            Ky9oSkNOcVRReStMREF6bzlsYi9mWVkKqKnt6Ih0rW1xrAYjWwRnJ5jMXZiGlSMi
            Jt3hJFqdQX6QHlxYGKoW44SFLFslHuElYCEx4PQUJ1XU+Baz4mU49g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T07:40:22Z"
    mac: ENC[AES256_GCM,data:FB3tCanUfuDBWjiGGT8Praeb+xG9e7LUc1Ltl/NKkW3eWvvBXEeIQYvQSHRNJJxPBicSXn6/ozmeVc9wuGicLIN211wPOQpEiJJJ/CyTyvTW8PZfGLOq/Et1WNdLG7Qz0UjA7/FMA4ElF2l/0th7YVtWIzFtfCWfcD8BhE16u70=,iv:1Y9VpfdQRks2BUPdIVEgU4cuG4Ysq4Ppo06Q6YkpqCg=,tag:v/eJhRG3DGvUq/MjXzXgqg==,type:str]
    pgp: []
    encrypted_regex: ^(env|admin|proxy|enterprise|manager|portal|portalapi|postgresql)$
    version: 3.7.3
