on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.assets/**'
      - .gitignore

jobs:
  deploy_to_cluster:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    environment: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: "18"
    - name: Install age
      run: |
        curl -Lo age.tar.gz https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
        tar xf age.tar.gz 
        sudo mv age/age /usr/local/bin
        sudo mv age/age-keygen /usr/local/bin
        age -version
    - name: Install sops
      run: |
        wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
        sudo mv sops-sops-v3.7.3.linux.amd64 /usr/local/bin/sops
        sops --version
    